title:              Shad's Data Science Blog
email:              shadfdz@gmail.com
description:        A Data Science Blog for the Masses
author:             Shad Fernandez
baseurl:            ""
url:                "https://shadfdz.github.io"

# Social Profiles
twitter_username:   
github_username:    shadfdz
facebook_username:  
instagram_username:  shad.meister
linkedin_username:  shad-fernandez

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
